spring.application.name=smart.lab
spring.datasource.url=jdbc:mysql://localhost:3306/smart_medical_lab
spring.datasource.username=root
spring.datasource.password=Sarjana@2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
logging.level.org.springframework.security=DEBUG
logging.level.root=INFO
logging.level.com.smart=INFO
logging.file.name=logs/smart-medical-lab.log